# 순환 신경망 활용

# 목차

# 임베딩<sup>Embedding</sup>

## 임베딩<sup>Embedding</sup>이란?
컴퓨터가 이해하는 벡터로 변경하는 것
- 단어 수준 임베딩  
  - 동음이의어를 구별 가능
  - Word2Vec, FastText
- 문장 수준 임베딩
  - 문장의 앞뒤를 보고 이를 파악할 수 있음
  - Elmo, Bert, GPT

간단한 단어 수준 임베딩에는 희소 행렬을 결과로 출력하는 원-핫 인코딩<sup>one-hot encoding</sup>이 있고,  
이와 반대로는 자원의 낭비가 적고 단어 사이의 유사도를 알 수 있는 밀집 행렬로 단어를 표현할 수 있다.

In [2]:
# Keras 라이브러리를 이용하여 밀집 행렬로 단어 수준 임베딩하기
# 라이브러리 불러오기
import tensorflow as tf

# 임베딩 레이어
embedding_layer = tf.keras.layers.Embedding(100, 3)
result = embedding_layer(tf.constant([12, 8, 15, 20]))
print(result)

tf.Tensor(
[[ 0.01936314  0.02011268  0.00141933]
 [-0.01075004  0.03470894  0.03640759]
 [-0.03879552  0.0181275  -0.02100657]
 [ 0.01774385 -0.03633636  0.0420985 ]], shape=(4, 3), dtype=float32)


Keras 에서 제공하는 Embedding Layer
  - input_dim : 단어 사전의 크기
  - output_dim : 출력 벡터의 크기
  - input_length : 입력 길이 ( = 문장 내 단어의 개수)

In [4]:
# 임베딩 레이어를 활용한 RNN
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(100, 1, input_length=32))
model.add(tf.keras.layers.LSTM(units=32))
model.add(tf.keras.layers.Dense(units=1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 32, 1)             100       
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                4352      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 4,485
Trainable params: 4,485
Non-trainable params: 0
_________________________________________________________________


라이브러리 선 호출 방식

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# 임베딩 레이어 활용
model = Sequential()
model.add(Embedding(100, 3, input_length = 32))
model.add(LSTM(32))
model.add(Dense(1))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 32, 3)             300       
_________________________________________________________________
lstm_2 (LSTM)                (None, 32)                4608      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 4,941
Trainable params: 4,941
Non-trainable params: 0
_________________________________________________________________


# 양방향<sup>Bidirectional</sup> RNN
자연어 데이터의 경우 순서대로 데이터를 처리하고, 역순으로도 처리할 경우 더 좋은 성능을 발휘하기도 한다.

In [10]:
# Bidirectional LSTM
from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Embedding(100, 3))
model.add(Bidirectional(LSTM(32)))
model.add(Dense(1))

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, None, 3)           300       
_________________________________________________________________
bidirectional_2 (Bidirection (None, 64)                9216      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
Total params: 9,581
Trainable params: 9,581
Non-trainable params: 0
_________________________________________________________________


# 스태킹 RNN
RNN layer를 여러 층 쌓기 위해서는 기본적으로 마지막 상태 값만 출력하는 RNN layer의 옵션을 변경해야한다.
 

In [12]:
# 스태킹 RNN 예제
model = Sequential()
model.add(Embedding(100, 32))
model.add(LSTM(32, return_sequences=True))
model.add(LSTM(32))
model.add(Dense(1))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, None, 32)          3200      
_________________________________________________________________
lstm_8 (LSTM)                (None, None, 32)          8320      
_________________________________________________________________
lstm_9 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 33        
Total params: 19,873
Trainable params: 19,873
Non-trainable params: 0
_________________________________________________________________


# 순환 드롭아웃
내장 RNN은 순환 상태의 드롭아웃 비율을 뜻하는 recurrent_dropout을 제공하고 있다.  
0과 1사이의 부동 소수점이고 과대적합을 방지하기 위한 기능이다.

In [14]:
# 순환 드롭아웃
model = Sequential()
model.add(Embedding(100, 32))
model.add(LSTM(32, recurrent_dropout=0.2, dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, None, 32)          3200      
_________________________________________________________________
lstm_10 (LSTM)               (None, 32)                8320      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 33        
Total params: 11,553
Trainable params: 11,553
Non-trainable params: 0
_________________________________________________________________
